services:
  - type: web
    name: event-planning-assistant
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn Event_Plan.app:app"
    envVars:
      - key: FLASK_ENV
        value: production

